### ISSUE TITLE
AppVeyor Warning: $ENV:BHPSModulePath is deprecated and will be removed July 1st, 2017

### ISSUE THREAD

**Issue by JohnLBevan** [AtlassianPS/JiraPS#113]
Currently AppVeyor builds are giving a warning stating that we're using a deprecated feature / due to expire in < 2 months.

I've not found any documentation on this, but looking at the BuildHelpers code, it seems that when calling `Set-BuildEnvironment` we should supply a value for `VariableNamePrefix` (other than the default `BH` value) to avoid this warning / future issue.

Related BuildHelper code: https://github.com/RamblingCookieMonster/BuildHelpers/blob/9330287eaa8cb70450544321f2b8cf77ecf49bc9/BuildHelpers/Public/Set-BuildEnvironment.ps1

The line in our code causing this is in `build/build.settings.ps1`.
https://github.com/PSJira/PSJira/blob/9362313fb7e559fa9762954c5cce51311e371b08/build/build.settings.ps1

Suggest changing `Set-BuildEnvironment -Path $ProjectRoot` to `Set-BuildEnvironment -Path $ProjectRoot -VariableNamePrefix 'BHJIRA'`

This will also have knock on effects, such as `Write-Host "BuildHelpers environment:`n$(Get-Item env:bh* | Out-String)" -ForegroundColor Green` would need to be amended to use the new prefix (or not, if our prefix still begins BH).
Presumably `if ($env:BHBuildSystem -eq 'AppVeyor') {` would also need to be changed to `if ($env:BHJIRABuildSystem -eq 'AppVeyor') {`; etc.

**Comment by replicaJunction** [comment]
We're not actively using the deprecated variable - my understanding is that the new variable mentioned in that warning message, ```$ENV:BHModulePath```, will continue to function. (Actually, I'm not sure the build system even references that new variable.)

That said, I don't see an issue with your suggested fix of adding a prefix to the BH variables. At the very least, it will get rid of the ugly warning message.

**Comment by JohnLBevan** [comment]
@replicaJunction agreed; I realised after writing the fix that the warning actually explains the action required (i.e. to replace the BHPS... variable with it's BH... equivalent), but came to the same conclusion about the warning.
