### ISSUE TITLE
Improve paging of Invoke-JiraMethod

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#114]
### Description
The current implementation of `Invoke-JiraMethod` does not support paging.

### Suggestion
Implement a paging similar to the one in PR #75 to `Invoke-JiraMethod` in order for all functions to benefit from it.

### Additionally
`[CmdletBinding(SupportsPaging = $true)]` enables a function to support paging on itself.
This exposes parameters such as `-Skip`, `-IncludeTotalCount` and `-First`.
this could be implemented in the likes of:
```posh
$PSBoundParameters["Skip"] = $PSCmdlet.PagingParameters.Skip + $result.Count
$PSBoundParameters["First"] = $PSCmdlet.PagingParameters.First - $result.Count
Invoke-WikiMethod @PSBoundParameters
```

Other good sample:
https://github.com/PowerShell/PowerShell/blob/master/demos/rest/rest.ps1

**Comment by replicaJunction** [comment]
Wow, I didn't know about the SupportsPaging attribute...that's pretty cool.

I've got a local branch at home where I implemented a helper function called Get-JiraPageData. I'll push that branch this weekend (not merge it back in, just push) so you all can see it and see if it's useful for this. It's similar to #75 but a bit more generalized.

**Comment by JohnLBevan** [comment]
Related: brianbunke/ConfluencePS#50; this project would need to use exactly the same solution; so may be worth cross-pollinating?

**Comment by lipkau** [comment]
note: the json structure contains `"total": 200,` which should be used

**Comment by JohnLBevan** [comment]
Just to check, where did you see the `total` value?  Running `Invoke-WebRequest -Method get -uri 'https://myInstance.atlassian.net/rest/api/latest/user/search?username=J&maxResults=2' | select -ExpandProperty Content` I don't see it.  My guess in that only certain APIs return this?  Thanks in advance.

**Comment by JohnLBevan** [comment]
Ah; I get the expected value when using search: `/rest/api/2/search?...`.  I'll add code to check whether `total`, `startAt` and `maxResults` exist on the root of the result; if they do I'll treat `total` as a total; if not I'll calculate it & assign a suitable estimate value (i.e. based on the result size & whether or not it's smaller than the page size).

**Comment by lipkau** [comment]
This function can benefit from it:
https://github.com/AtlassianPS/JiraPS/blob/c70e8541952caaf8ce4ed47196cc184d6275297b/JiraPS/Public/Get-JiraGroupMember.ps1#L79-L136

**Comment by lipkau** [comment]
Add a parameter to show the progress (if available) - analog on how `Get-JiraIssue -Query` is doing it now
