### ISSUE TITLE
.\Tools\Pre-Push.ps1 :: WARNING: The -Quiet parameter has been deprecated

### ISSUE THREAD

**Issue by JohnLBevan** [AtlassianPS/JiraPS#117]
Running .\Tools\Pre-Push.ps1 gives warning:

`WARNING: The -Quiet parameter has been deprecated; please use the new -Show parameter instead. To get no output use -Show None.`

This relates to Pre-Push.ps1 line 7: `$pesterResults = Invoke-Pester -Quiet -PassThru`

Fix per warning is: `$pesterResults = Invoke-Pester -Show None -PassThru`

**Comment by lipkau** [comment]
This is no longer relevant with the new CI code
