### ISSUE TITLE
LICENSE in Module

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#123]
### Current Behavior
Currently the LICENSE is only declared in
* the repo's root 
* the module meta data (manifest) as url

### Possible Solution
Add a copy of the LICENSE file to the module root?

**Comment by lipkau** [comment]
@replicaJunction do you have an opinion on that?

**Comment by replicaJunction** [comment]
Makes sense to me. I don't see an issue with explicitly adding a LICENSE file.
