### ISSUE TITLE
its no possible to add worklog to an issue

### ISSUE THREAD

**Issue by brunoscota** [AtlassianPS/JiraPS#153]
### Expected Behavior
When I try to use "Add-JiraIssueWorklog", its not possible. It gives me an error

### Current Behavior
The following error appears:

Command:
`Get-JiraIssue GMUD-1253 | Add-JiraIssueWorklog -Comment "Gmud" -VisibleRole 'All Users' -TimeSpent 60 -DateStarted (Get-Date)`

`AVISO: JIRA returned HTTP error 500 - InternalServerError
ConvertTo-JiraWorklogItem : Não é possível associar o argumento ao parâmetro 'InputObject' porque ele é nulo.
No C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.1.0.90\Public\Add-JiraIssueWorklog.ps1:132 caractere:58
         $result = ConvertTo-JiraWorklogitem -InputObject $rawResult
                                                          ~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [ConvertTo-JiraWorklogItem], ParameterBindingValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-JiraWorklogItem`




### Your Environment

`Version
-------
2.1.0.90`

**Comment by brunoscota** [comment]
Using debug here what I got..

> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Add-JiraIssueWorklog] Preparing for blastoff!! {
>     "timeSpent":  "6E-06",
>     "started":  "05/07/2017 00:57:30",
>     "comment":  "Gmud",
>     "visibility":  {
>                        "value":  "Developers",
>                        "type":  "role"
>                    }
> }
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Get-JiraSession] Module private data exists
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Get-JiraSession] A Session object is saved; outputting
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Invoke-JiraMethod] A session was found; using saved session (Username=[bcarvalho], JSessionID=[])
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Invoke-JiraMethod] Invoking JIRA method Post to URI https://jira.neogrid.com/rest/api/latest/issue/891830/worklog
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"): S
> DEPURAR: [Invoke-JiraMethod] Status code: InternalServerError
> 
> Confirmar
> Continuar com essa operação?
> [S] Sim  [A] Sim para Todos  [P] Parar Comando  [U] Suspender  [?] Ajuda (o padrão é "S"):

**Comment by brunoscota** [comment]
Found the issue!

its here:

DEPURAR: [Add-JiraIssueWorklog] Preparing for blastoff!! 
    "timeSpentSeconds":  "6E-06",                        
    "started":  "05/07/2017 02:32:14",                   
    "comment":  "Gmud"                                   
}                                                        

worklog schema is waiting for String type but the module can't translate to it. See
`        "started": {
            "type": "string"
        },
        "timeSpent": {
            "type": "string"
        },`


This convertion its not working:
`
        $props = @{
            'comment'   = $Comment;
            'started'   = $DateStarted.ToString();
            'timeSpent' = $TimeSpent.ToString();
        }
`

I changed the script to consider the new values.. the post body MUST be at least
`{
    "timeSpent":"60",
    "comment": "I did some work here.",
    "started": "2017-07-05T13:12:36.317+0000"
}`


May I contribute for the Module, sending a pull request ?

**Comment by brunoscota** [comment]
I suggest to change in "Add-JiraIssueWorklog.ps1"
`[TimeSpan] $TimeSpent` to `[String] $TimeSpent`

and 
`'started'   = $DateStarted.tostring()` to `'started'   = $DateStarted.tostring("yyyy-MM-ddTHH:mm:ss.00+0000")`

**Comment by lipkau** [comment]
Hi Bruno.
Changing it to string is not the best way to go about it from our point of view.
If we would allow a string, any value could be provide. Such as `-TimeSpent "hello world"`.

Also, doing some such as `-TimeSpent "60" ` is bad practice. How would powershell (or jira) know if those were 60 days or 60 hours or 60 minutes or 60 seconds or 60 ticks?

We will add more example to that function.

**Comment by brunoscota** [comment]
HI lipkau,

Thank you for your review. I agree with you, but i'm following the way as Jira's AddWorklog API works. Lets take an example. 

As (https://docs.atlassian.com/jira/REST/server/#api/2/issue-addWorklog) mentioned in AddWorklog schema, timeSpent is a string type.

`        "timeSpent": {
            "type": "string"
        },`

But, what kind of string is that, how do I insert the string. Now, taking a look to Worklog at Jira's intarface you'll see a very perfecty example: 

![image](https://user-images.githubusercontent.com/5567091/27969078-eb44328c-631f-11e7-8267-2a3d612aa89b.png)

So, replying your question:

> How would powershell (or jira) know if those were 60 days or 60 hours or 60 minutes or 60 seconds or 60 ticks?

Its easy, just insert "60d 60h 60m 60s". Simply like that. But I made a mistake when i didn't update the docuementation and the exemples part.

In addition.. 

The APi will throw an exception when you try to insert "hello world". So, even if your force the error, the worklog will not be affected.

Sry for any inconvenience

**Comment by lipkau** [comment]
Jira accepts string, because as the payload is sent in json, no other format is feasible.
In powershell we have these many object types with specific usages. We should not change how to powershell because of the way the API works. Else we would not need the module.

When we use type datetime for a parameter, it is not only to ensure the right type of data is provided by the user, but rather for the user to use the benefits of the object.

In the case of timespan, you can easily fix the problem by casting the string to the object `-TimeSpent [timespan]"12:34:56"`.
However... if you would do more fancy stuff, like use the object to modify the value, you would struggle with a string:
```posh
$stopwatch = [timespan]how longer the user was online
$stopwatch.subtract("01:00") #lunch break
If ($stopwatch.hours -gt 8) {
    Write-Warning "user took too long"
}
# use $stopwatch for worklogitem 
```

**Comment by brunoscota** [comment]
I just thought it'll be easier to work as  Jira's worklog works, mainly for people who's familiar with Jira's data types. It could be a little confusing, you know. 
And, I don't know for you, but to me, this module has more sense that just modifying data types. 

But ok, don't worry, forget about it. You can close this discussion.

Thank you very much for you patiance.
