### ISSUE TITLE
Project versions

### ISSUE THREAD

**Issue by mwoffenden** [AtlassianPS/JiraPS#159]
How do I get a Jira project's _versions_ using JiraPS?

**Comment by lipkau** [comment]
`Get-JiraVersion -Project $ProjectKey`.
But this is currently only available in de _dev_ branch.
Don't know if I will manage to release this to the gallery tomorrow. But within the next month definitely.

**Comment by mwoffenden** [comment]
In Jira it's possible to create multiple versions for a project.  Would this give me a list of all versions for a project?

**Comment by lipkau** [comment]
Yes

**Comment by mwoffenden** [comment]
Great.  How do I access the dev branch?

**Comment by lipkau** [comment]
https://github.com/AtlassianPS/JiraPS/archive/dev.zip

**Comment by mwoffenden** [comment]
Great, how do I install?

**Comment by lipkau** [comment]
You can `Import-Module '......\JiraPS\JiraPS.psd1'`

**Comment by mwoffenden** [comment]
Ok, I imported the module and the **Get-JiraVersion** command is available.

Bit it's not finding my project, which I know exists (and I can retrieve the project name using Get-JiraProject.)  Getting this error.  Any ideas?

Resolve-JiraError : Jira encountered an error: [No project could be found with key 'Project1'.]

**Comment by lipkau** [comment]
Can you show a screenshot of the Versions?

**Comment by Dejulia489** [comment]
Get-JiraProject -Project 'Project1'  |  Get-JiraVersion

**Comment by mwoffenden** [comment]
<img width="1420" alt="screenshot_753" src="https://user-images.githubusercontent.com/6774346/28837680-ad7aaeae-76bb-11e7-8586-492dfcf479f2.png">

**Comment by mwoffenden** [comment]
Some progress.  I can retrieve individual versions with this command:

Get-JiraVersion -ID 10001 -Credential $cred

But I am still struggling to access all versions by Project name.

**Comment by lipkau** [comment]
Unfortunately you redacted the project key

**Comment by mwoffenden** [comment]
Yes, we can't post it.  How would it help you anyway?

**Comment by lipkau** [comment]
I am sorry to say, but I am not able to track down the problem
please make sure your prokect key is in the correct case (I think the current implementation is case sensitive).
![image](https://user-images.githubusercontent.com/4992870/28846006-27bb0d82-770a-11e7-93d3-190eb0b5eddf.png)

However: I am planing on releasing the a new version by end of this week with the feature working properly.
You can track this here:  [Milestone v2.2](https://github.com/AtlassianPS/JiraPS/milestone/4)

**Comment by mwoffenden** [comment]
I do have the key in the correct case.  Hope the new release fixes my issue.
