### ISSUE TITLE
Typo in tests - $results

### ISSUE THREAD

**Issue by kbakk** [AtlassianPS/JiraPS#164]
The following lines seems to have a typo - `$results` vs `$result`.

https://github.com/AtlassianPS/JiraPS/blob/928c9fc3a9e3b3c6689c34ec99e49cc828063a75/Tests/New-JiraVersion.Tests.ps1#L102-L103

https://github.com/AtlassianPS/JiraPS/blob/928c9fc3a9e3b3c6689c34ec99e49cc828063a75/Tests/New-JiraVersion.Tests.ps1#L108-L109

https://github.com/AtlassianPS/JiraPS/blob/928c9fc3a9e3b3c6689c34ec99e49cc828063a75/Tests/New-JiraVersion.Tests.ps1#L126-L127

**Comment by lipkau** [comment]
Thank you for reporting this, @kbakk 
As it has no impact on the module's behavior, I don't see it as critical to publish it right away.
but it will be published, once we get appveyor to publish to the Gallery again
