### ISSUE TITLE
Get-JiraIssueCreateMetadata returns "Get-Member : You must specify an object for the Get-Member cmdlet."

### ISSUE THREAD

**Issue by monahancj** [AtlassianPS/JiraPS#176]
### Expected Behavior
Get-JiraIssueCreateMetadata should return data.

### Current Behavior
Get-JiraIssueCreateMetadata returns a PowerShell error.

### Possible Solution
My assumption is that on line 34 the statement "$i.projects.issuetypes.fields" doesn't return data leaving $fields empty.

### Steps to Reproduce (for bugs)
```
$> Get-JiraIssueCreateMetadata -Project OPS -IssueType Task
Get-Member : You must specify an object for the Get-Member cmdlet.
At P:\My Documents\WindowsPowerShell\Modules\JiraPS\2.2.0.141\Internal\ConvertTo-JiraCreateMetaField.ps1:35 char:32
+ ... eldNames = (Get-Member -InputObject $fields -MemberType '*Property'). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
```

### Context
I'm running through the Introduction and got to here: http://psjira.readthedocs.io/en/latest/creating_issues.html .  All the previous commands have worked.

### Your Environment
My desktop computer is Windows 10, 4 core and 32gb RAM.

PowerShell commands running in the default 64-bit console window.  Not running in any special PowerShell host, or in an editor's console window.

JIRA server v6.4.  The front end is running on Microsoft Windows Server 2012 (64-bit), and the database is running on CentOS 6 (64-bit).  Both servers are full patched.

=================================================
$> Get-Module JiraPS -ListAvailable | select version

Version
-------
2.2.0.141
2.2.0.141

$> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.1106
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.1106
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lipkau** [comment]
Is this a Service Desk project?

**Comment by monahancj** [comment]
I'm 99% sure it's "Jira Software - Project and issue tracking".

**Comment by monahancj** [comment]
I ran the command again with -debug and -verbose.

============================================

$> Get-JiraIssueCreateMetadata -Project OPS -IssueType Task -Debug -Verbose
DEBUG: [Get-JiraIssueCreateMetadata] Reading server from config file

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraConfigServer] Found Server element. Outputting.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Building URI for REST call based on parameters

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Obtaining project ID for project [OPS]

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraProject] Reading server from config file

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraConfigServer] Found Server element. Outputting.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraProject] Processing project [OPS]

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraProject] Preparing for blastoff!

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] Module private data exists

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] A Session object is saved; outputting

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[theusername], JSessionID=[])

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: Using saved Web session with username theusername
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.companyname.com:8443/rest/api/latest/project/OPS?expand=projectKeys

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: GET https://jira.companyname.com:8443/rest/api/latest/project/OPS?expand=projectKeys with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
DEBUG: [Invoke-JiraMethod] Status code: 200

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraProject] Converting to object

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraProject] Outputting result

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: Complete

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Obtaining issue type ID for issue type [Task]

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Reading server from config file

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraConfigServer] Found Server element. Outputting.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Obtaining all issue types from Jira

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] Module private data exists

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] A Session object is saved; outputting

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[theusername], JSessionID=[])

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: Using saved Web session with username theusername
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.companyname.com:8443/rest/api/latest/issuetype

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: GET https://jira.companyname.com:8443/rest/api/latest/issuetype with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
DEBUG: [Invoke-JiraMethod] Status code: 200

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Processing issue type [Task]

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Searching for issue type (name=[Task])

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Found results; outputting

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: Complete

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Preparing for blastoff!

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] Module private data exists

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraSession] A Session object is saved; outputting

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[theusername], JSessionID=[])

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: Using saved Web session with username theusername
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.companyname.com:8443/rest/api/latest/issue/createmeta?projectIds=10204&issuetypeIds=3&expand=projects.issuetypes.fields

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: GET https://jira.companyname.com:8443/rest/api/latest/issue/createmeta?projectIds=10204&issuetypeIds=3&expand=projects.issuetypes.fields with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
DEBUG: [Invoke-JiraMethod] Status code: 200

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Identified project key: [OPS]

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueCreateMetadata] Converting results to custom object

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ConvertTo-JiraCreateMetaField] Processing object: '@{expand=projects; projects=}'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
Get-Member : You must specify an object for the Get-Member cmdlet.
At P:\My Documents\WindowsPowerShell\Modules\JiraPS\2.2.0.141\Internal\ConvertTo-JiraCreateMetaField.ps1:35 char:32
+ ... eldNames = (Get-Member -InputObject $fields -MemberType '*Property'). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

DEBUG: Outputting results

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
[10:50:09] - [] - [D:] aa
$>

**Comment by lipkau** [comment]
Please try opening this url in a browser (_where you are already loged in_):
 https://jira.companyname.com:8443/rest/api/latest/issue/createmeta?projectIds=10204&issuetypeIds=3&expand=projects.issuetypes.fields

**Comment by monahancj** [comment]
It worked.

expand	"projects"
projects	
  0	
    expand	"issuetypes"
    self	"https://jira.companyname.com:8443/rest/api/2/project/10204"
    id	"10204"
    key	"OPS"
    name	"Operations"
    avatarUrls	
      48x48	"https://jira.companyname.com:8443/secure/projectavatar?pid=10204&avatarId=10205"
      24x24	"https://jira.companyname.com:8443/secure/projectavatar?size=small&pid=10204&avatarId=10205"
      16x16	"https://jira.companyname.com:8443/secure/projectavatar?size=xsmall&pid=10204&avatarId=10205"
      32x32	"https://jira.companyname.com:8443/secure/projectavatar?size=medium&pid=10204&avatarId=10205"
      issuetypes

**Comment by lipkau** [comment]
Why is that not json formatted?

**Comment by lipkau** [comment]
What about:
https://jira.companyname.com:8443/rest/api/2/issuetype/3
And:
```
Get-JiraIssueType 3
```

**Comment by monahancj** [comment]
I think it is but the formatting was lost when I copied it to notepad to do a search/replace in the URL.  I pasted it straight in and manually did the search replace.

**Comment by monahancj** [comment]
self | "https://jira.companyname.com:8443/rest/api/2/issuetype/3"
-- | --
id | "3"
description | "A task that needs to be done."
iconUrl | "https://jira.companyname.com:8443/images/icons/issuetypes/task.png"
name | "Task"
subtask | false


======================================
No output from the powershell command.

[10:50:09] - [] - [D:] aa
$>
[10:50:09] - [] - [D:] aa
$> Get-JiraIssueType 3
[11:22:11] - [] - [D:] aa
$> Get-JiraIssueType 3 | fl *
[11:23:19] - [] - [D:] aa
$>

**Comment by lipkau** [comment]
This looks really weird.
Please take a screenshot of https://jira.companyname.com:8443/rest/api/2/issuetype/3

**Comment by monahancj** [comment]
![github_jiraps_issue176](https://user-images.githubusercontent.com/5665684/30552606-8e534c8a-9c6c-11e7-96cc-d0df1c9c26fc.jpg)

**Comment by lipkau** [comment]
Ok... so first of: please use the "Raw Data" tab when pasting results here.

Now... try this and send me the output:
```posh
Get-JiraIssueType 3 -debug
# enter suspend mode after this message: [Get-JiraIssueType] Obtaining all issue types from Jira
Invoke-JiraMethod -Method Get -URI $uri -Credential $Credential
```

**Comment by monahancj** [comment]
Hello again.  Thanks for your help with this.

=============================================

$> Get-JiraIssueType 3 -Debug
DEBUG: [Get-JiraIssueType] Reading server from config file

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraConfigServer] Found Server element. Outputting.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Get-JiraIssueType] Obtaining all issue types from Jira

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): s
[11:38:48] - [] - [D:] aa
$> Invoke-JiraMethod -Method Get -URI $uri -Credential $credsjira
DEBUG: [Invoke-JiraMethod] Using HTTP Basic authentication with provided credentials for _cmonahan

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.companyname.com:8443/rest/api/latest/issuetype

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Status code: 200

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):


self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/1
id          : 1
description : A problem which impairs or prevents the functions of the product.
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/bug.png
name        : Bug
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10100
id          : 10100
description : A task that needs to be done
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype
name        : Chore
subtask     : False
avatarId    : 10318

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/5
id          : 5
description : The sub-task of the issue
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/subtask_alternate.png
name        : Sub-task
subtask     : True

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10000
id          : 10000
description : Created by JIRA Agile - do not edit or delete. Issue type for a big user story that needs to be broken down.
iconUrl     : https://jira.companyname.com:8443/images/icons/ico_epic.png
name        : Epic
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10001
id          : 10001
description : Created by JIRA Agile - do not edit or delete. Issue type for a user story.
iconUrl     : https://jira.companyname.com:8443/images/icons/ico_story.png
name        : Story
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10101
id          : 10101
description : Issue type for investigation efforts which includes technical and functional spike types
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Spike
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10400
id          : 10400
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Creative Brief
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/3
id          : 3
description : A task that needs to be done.
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/task.png
name        : Task
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10500
id          : 10500
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10303&avatarType=issuetype
name        : Error
subtask     : False
avatarId    : 10303

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10501
id          : 10501
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Effort
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10200
id          : 10200
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Request
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10201
id          : 10201
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Defect
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10202
id          : 10202
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Enhancement
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10601
id          : 10601
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : GCS Task
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10600
id          : 10600
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : GCS Request
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/2
id          : 2
description : A new feature of the product, which has yet to be developed.
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/newfeature.png
name        : New Feature
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/4
id          : 4
description : An improvement or enhancement to an existing feature or task.
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/improvement.png
name        : Improvement
subtask     : False

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10002
id          : 10002
description : Created by JIRA Agile - do not edit or delete. Issue type for a technical task.
iconUrl     : https://jira.companyname.com:8443/images/icons/ico_task.png
name        : Technical task
subtask     : True

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10300
id          : 10300
description :
iconUrl     : https://jira.companyname.com:8443/images/icons/issuetypes/genericissue.png
name        : Documentation
subtask     : False

[11:39:09] - [] - [D:] aa
$>

**Comment by lipkau** [comment]
Please show me the result of (where `$projectKey` is the project in question)
```powershell
Get-JiraProject $projectKey
```

**Comment by monahancj** [comment]
Thank you for your help.

`$> Get-JiraProject | ? { $_.Key -eq 'OPS' }

ID          : 10204
Category    :
IssueTypes  :
RestUrl     : https://jira.companyname.com:8443/rest/api/2/project/10204
Key         : OPS
Components  :
Name        : Operations
Description :
Roles       :



$> Get-JiraProject OPS

ID          : 10204
Category    :
IssueTypes  : {@{self=https://jira.companyname.com:8443/rest/api/latest/issuetype/10200; id=10200; description=; iconUrl=https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype; name=Request;
              subtask=False; avatarId=10300}, @{self=https://jira.companyname.com:8443/rest/api/latest/issuetype/5; id=5; description=The sub-task of the issue;
              iconUrl=https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10316&avatarType=issuetype; name=Sub-task; subtask=True; avatarId=10316}}
RestUrl     : https://jira.companyname.com:8443/rest/api/latest/project/10204
Key         : OPS
Components  : {@{self=https://jira.companyname.com:8443/rest/api/2/component/11248; id=11248; name=_OPS User Account Management; description=Requests for Changes to LDAP and Active Directory Accounts. ; isAssigneeTypeValid=False},
              @{self=https://jira.companyname.com:8443/rest/api/2/component/11246; id=11246; name=_SSL Certificate Administation; description=SSL certificate requests ; isAssigneeTypeValid=False},
              @{self=https://jira.companyname.com:8443/rest/api/2/component/13715; id=13715; name=_Third Party DNS; isAssigneeTypeValid=False}, @{self=https://jira.companyname.com:8443/rest/api/2/component/11247; id=11247; name=_Unix
              DNS Administation; description=DNS Requests for domains managed by the unix team.  This includes all externally facing domains and companyname.com; isAssigneeTypeValid=False}...}
Name        : Operations
Description :
Roles       : @{Team Lead=https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10002; Stakeholder=https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10402;
              Developers=https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10800; System Users=https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10000; Team
              Member=https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10001}



$> (Get-JiraProject OPS).IssueTypes

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10200
id          : 10200
description :
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
name        : Request
subtask     : False
avatarId    : 10300

self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/5
id          : 5
description : The sub-task of the issue
iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10316&avatarType=issuetype
name        : Sub-task
subtask     : True
avatarId    : 10316



[13:48:23] - [] - [D:] aa
$> (Get-JiraProject OPS).Components


self                : https://jira.companyname.com:8443/rest/api/2/component/11248
id                  : 11248
name                : _OPS User Account Management
description         : Requests for Changes to LDAP and Active Directory Accounts.
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/11246
id                  : 11246
name                : _SSL Certificate Administation
description         : SSL certificate requests
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/13715
id                  : 13715
name                : _Third Party DNS
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/11247
id                  : 11247
name                : _Unix DNS Administation
description         : DNS Requests for domains managed by the unix team.  This includes all externally facing domains and companyname.com
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/14900
id                  : 14900
name                : AWS Support
description         : Operations Support for AWS Environments
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/12403
id                  : 12403
name                : DC Asset Management
description         : Requests for Rack space and Server Moves.
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10524
id                  : 10524
name                : Global Operations Center
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/15206
id                  : 15206
name                : Incident Management
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/13307
id                  : 13307
name                : ITHC 2016
description         : ITHC 2016 Health check Items
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/11410
id                  : 11410
name                : Network Team - Server Decom
description         : Component for the Network Team's steps in the server decommission process
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/12026
id                  : 12026
name                : PCI Audit Findings
description         : PCI Audit Compliance Findings and Remediation
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10526
id                  : 10526
name                : Security Scan Vulnerability
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/11402
id                  : 11402
name                : SysAdmin-Backup
description         : Backup Requests
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/12251
id                  : 12251
name                : Sysadmin-DevOps
description         : Operations Devops and automation work
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10519
id                  : 10519
name                : Sysadmin-Infrastructure-EU
description         : Generic requests for assistance from the EU Windows Team
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10523
id                  : 10523
name                : SysAdmin-Monitoring
description         : Changes to System Monitoring
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10521
id                  : 10521
name                : Sysadmin-Storage
description         : Storage Administration and troubleshooting
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10520
id                  : 10520
name                : SysAdmin-Unix
description         : Generic requests for assistance from the Unix teams
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10522
id                  : 10522
name                : SysAdmin-VMWare
description         : Generic requests for assitance from the VM Team
isAssigneeTypeValid : False

self                : https://jira.companyname.com:8443/rest/api/2/component/10518
id                  : 10518
name                : SysAdmin-Windows
description         : Generic requests for assistance from the NA Windows Team
isAssigneeTypeValid : False



$> (Get-JiraProject OPS).Roles

Team Lead    : https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10002
Stakeholder  : https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10402
Developers   : https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10800
System Users : https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10000
Team Member  : https://jira.companyname.com:8443/rest/api/latest/project/10204/role/10001`

**Comment by lipkau** [comment]
This is so weird...
try these url in a browser that is already log in to you jira server:

https://jira.companyname.com:8443/rest/api/latest/issue/createmeta?projectIds=10204&issuetypeIds=5&expand=projects.issuetypes.fields
https://jira.companyname.com:8443/rest/api/latest/issue/createmeta?projectIds=10204&issuetypeIds=10200&expand=projects.issuetypes.fields

**Comment by lipkau** [comment]
Hold on... I think I got it...

This nip of yours:
> ```powershell
$> (Get-JiraProject OPS).IssueTypes
> 
> self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/10200
> id          : 10200
> description :
> iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10300&avatarType=issuetype
> name        : Request
> subtask     : False
> avatarId    : 10300
> 
> self        : https://jira.companyname.com:8443/rest/api/latest/issuetype/5
> id          : 5
> description : The sub-task of the issue
> iconUrl     : https://jira.companyname.com:8443/secure/viewavatar?size=xsmall&avatarId=10316&avatarType=issuetype
> name        : Sub-task
> subtask     : True
> avatarId    : 10316
> ```

tells me, that this project has 2 issue types:
* Sub-Task
* Request

However, in your original command, you are trying to create a type `Task`, which is not in the list above
> ```powershell
> $> Get-JiraIssueCreateMetadata -Project OPS -IssueType Task
> ```

**Comment by monahancj** [comment]
That was it.  Using "-IssueType Request" works.  Thank you for all your help.
