### ISSUE TITLE
Cannot determine syntax for a system priority when used as a field with set-jiraissue

### ISSUE THREAD

**Issue by msacademy** [AtlassianPS/JiraPS#180]
Need to be able to update priority with set-jiraussue

### Expected Behavior
get-JiraIssue  ITSUP-5104 | select priority

priority                                                                                                                                                                  
--------                                                                                                                                                                  
@{self=https://bolderthinking.atlassian.net/rest/api/2/priority/2; iconUrl=https://bolderthinking.atlassian.net/images/icons/priorities/critical.svg; name=Critical; id=2}

I expect I can put that entire string in fields and have it work

### Current Behavior
Set-JiraIssue -Issue ITSUP-5104   -fields $fields
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [priority] - Could not find valid 'id' or 'name' in priority object.
At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Internal\Invoke-JiraMethod.ps1:112 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError
### Possible Solution
Clear documentation on this type of field on how to do syntax

### Steps to Reproduce (for bugs)
see above

### Context
I am trying to update issues with set-jiraissue and priority is a field I need

### Your Environment
n/a

**Comment by msacademy** [comment]
I found it.  
'Priority' = @{
    name = $priority
    }
I just needed to pull either the name or the id from the url

**Comment by lipkau** [comment]
I am glad you found the correct format for that scenario.
I reopened the issue so that we use this issue to track the documentation of this.
