### ISSUE TITLE
How do I determine the set-jiraussue value of a custom field (option2)

### ISSUE THREAD

**Issue by msacademy** [AtlassianPS/JiraPS#181]
I have an 'option2' type of dropdown field.  I can see rthe values on the browser dropdown.  I should be able to plug a value in the powershell command,

### Expected Behavior
> ID          : customfield_11501
> Searchable  : True
> Schema      : @{type=option2; custom=com.atlassian.plugins.atlassian-connect-plugin:io.tempo.jira__account; 
>               customId=11501}
> Name        : Account
> Custom      : True
> Navigable   : True
> Orderable   : True
> ClauseNames : {Account, cf[11501]}

The value 'Humach', is one account for example.

### Current Behavior
```powershell
$fields = @{
    customfield_11501 = @{
    name = 'Account'
    value = 'Humach'
    }
}
```

or just

```powershell
$fields = @{
    customfield_11501 = @{
    value = 'Humach'
    }
}
```

But the error is:

> PS C:\Windows\system32> set-jiraissue ITSUP-5104 -field $fields
> WARNING: JIRA returned HTTP error 400 - BadRequest
> Resolve-JiraError : Jira encountered an error: [io.tempo.jira__account] - Can not deserialize instance of java.lang.Long out of START_OBJECT token
>  at [Source: N/A; line: -1, column: -1]
> At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Internal\Invoke-JiraMethod.ps1:112 char:13
> +             Resolve-JiraError $result -WriteError
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError

 I also tried:
```powershell
$fields = @{
   customfield_11501 = @(@{
    name = 'Account'
    value = 'Humach'
    })
}
```
but got:
> set-jiraissue ITSUP-5104 -field $fields
> WARNING: JIRA returned HTTP error 400 - BadRequest

### Possible Solution
A documentation example of a single select field for -fields.  And how to find the possible values as ID's.

### Steps to Reproduce (for bugs)
See above

### Context
I need to create issues and assign them to one of 20 accounts.

### Your Environment
n/a

**Comment by lipkau** [comment]
The Schema of the field tells us, that it's not a native field type; but one added by a plugin.
This module does not support plugins, as it would get out of hand **very** quickly.

However, this is what you can do (_given you have the ID of that account_, in this example it's 69):
```powershell
-Fields @{customfield_11501 = "69"}
```

**Comment by msacademy** [comment]
That syntax did not work.



S C:\Windows\system32> set-jiraissue ITSUP-5104 -fields @{customfield_11501 = "69"}

WARNING: JIRA returned HTTP error 400 - BadRequest

Resolve-JiraError : Jira encountered an error: [Option with id 69 not found]

At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Internal\Invoke-JiraMethod.ps1:112 char:13

+ Resolve-JiraError $result -WriteError

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException

+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError

[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625<tel:641.243.8293;6625>

www.humach.co<http://www.humach.com/>m
Sent from iPad

On Sep 26, 2017, at 1:07 AM, Oliver Lipkau <notifications@github.com<mailto:notifications@github.com>> wrote:


The Schema of the field tells us, that it's not a native field type; but one added by a plugin.
This module does not support plugins, as it would get out of hand very quickly.

However, this is what you can do (given you have the ID of that account, in this example it's 69):

-Fields @{customfield_11501 = "69"}

**Comment by lipkau** [comment]
You do need to find the ID of the account first... as I said, that example used the ID 69... 
The link has the API of you to find the ID

**Comment by msacademy** [comment]
Not sure I understand.


PS C:\Windows\system32> get-jirafield account

　

ID : customfield_11501

Searchable : True

Schema : @{type=option2; custom=com.atlassian.plugins.atlassian-connect-plugin:io.tempo.jira__account;

customId=11501}

Name : Account

Custom : True

Navigable : True

Orderable : True

ClauseNames : {Account, cf[11501]}



The ID is customfield_11501 as far as I can tell.  How can I tell what the "values" are by ID's, if that is what they are called in the drop down?


[cid:f328a4cb-ebec-4b67-9bc4-6b20592ad5a8]





[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________

**Comment by lipkau** [comment]
That is the ID of the field.
you need the ID of the account. you need to use the api I gave you before to be able to retrieve the accountID of the account you want to set.

@thefonz: did you write a function for this?

**Comment by msacademy** [comment]
I do not see a link to the API to find that.


Well, let's just look at an existing value:

get-jiraissue ITSUP-5159 | select *


customfield_11501             : @{id=15; value=Humach}


So I tried:


$fields = @{

id='15'

value='Humach'}


set-jiraissue ITSUP-5104 -fields $fields



But got:


Unable to identify field [id] from -Fields hashtable. Use Get-JiraField for more information.
At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Public\Set-JiraIssue.ps1:176 char:29
+ ...             throw "Unable to identify field [$name] from -Fields hash ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to ident...re information.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to identify field [id] from -Fields hashtable. Use Get-JiraField for more i
   nformation.



[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________

**Comment by msacademy** [comment]
When I do a get-jirafields, I see:


ID          : customfield_11501
Searchable  : True
Schema      : @{type=option2; custom=com.atlassian.plugins.atlassian-connect-plugin:io.tempo.jira__account;
              customId=11501}
Name        : Account
Custom      : True
Navigable   : True
Orderable   : True
ClauseNames : {Account, cf[11501]}




[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________

**Comment by lipkau** [comment]
As I told you before.. the format is 
```
-Fields @{customfield_11501 = "<ID as an integer>"}
```

which, according to you sample, would translate to
```
-Fields @{customfield_11501 = "15"}
```

**Comment by msacademy** [comment]
Thank you.  It is now sinking in and that worked.  I am having to learn the Jira schema stuff fast.  I will say that this was a wonderful project and very well done in Powershell.  I have been able to create the issues I need from a template script thank to JiraPS project.



One last question (and I thank you for your patience).  What command can I use to get the ID "values" for each of the "Account" values in the custom field?  Or do I have to go into the Jira browser and figure it out (since it is part of a plugin as you mentioned)?  I just inherited Jira administration due to turnover so I apologize for not understanding everything.  I think this is the last piece and I will have a complete script to use.


Thank you again for your help.



[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________

**Comment by lipkau** [comment]
There is an API to get the full list of accounts... so a function would have to be written to execute this API call... for example:
```
$accounts = Get-Accounts
($accounts | where name -like "Humach").id
```

However, this function `Get-Accounts` needs to be written... lets see how @tehfonz solved this... as had this same issue (same plugin)

**Comment by tehfonz** [comment]
```
Function Get-JIRAAccountID ($prefix) {
	Switch -Regex ($prefix) {
		"AAA" {"64"}
		"BBB" {"65"}
		"CCC" {"66"}
		"DDD" {"67"}
		"EEE" {"75"}
		"FFF" {"69"}
		"GGG" {"70"}
		"HHH" {"71"}
		"III" {"68"}
		"JJJ" {"74"}
		"KKK" {"72"}
		"LLL" {"73"}
	}
}
```
I use the above function as such:
```$AccountField = Get-JIRAAccountID $Usernameprefix```

The ID (in curly braces) in the switch is the ID matching in JIRA. So far all I've done is make the ID dynamic, so if you change the $usernameprefix variable it will populate the $AccountField variable with the appropriate ID.

```Get-JiraIssue -Key <KEY> | select customfield_10012```
Change customfield_10012 to the field that has the ID you are after
for me this returns
```customfield_10012 : @{self=http://jiraURL.com/rest/tempo-accounts/1/account/69; id=69; key=FFF; name=FFF}```
This is how I've managed to get all the IDs I will ever need, as new ones are added I first add them to a JIRA issue, then run the Get-JiraIssue and select the CustomField_10012 to see what the new ID is, usually just the next in line (i.e. 74 will be the next one).
from here I am able to populate that field as such:
```Fields      = @{'customfield_10012' = "$AccountField"}```

The above is part of my splatted New-JiraIssue: which looks like this:

```
$NewJiraAMRecord = @{
	Project     = 'AM'
	IssueType   = 'Special Account'
	Summary     = "$Username"
	Description = "$Username"
	Reporter    = '<username>'
	Fields      = @{'customfield_10012' = "$AccountField"; 'customfield_10901' = "$Username"; 'customfield_11025' = "$SNREQ"; 'customfield_11202' = @{id = '11107'}}
}
```

Hope this helps.

Cheers!

**Comment by tehfonz** [comment]
A Tempo Account ID can be retrieved via the following JiraPS cmdlet:
`(Invoke-JiraMethod -Method GET -URI 'http://<JIRAURL>/rest/tempo-accounts/1/account' | Where-Object {$_.key -eq '<KEY>'}).id`

If you want all the information pertaining to the key  /  Account:
`Invoke-JiraMethod -Method GET -URI 'http://<JIRAURL>/rest/tempo-accounts/1/account' | Where-Object {$_.key -eq '<KEY>'}`

If you want to return all Tempo Accounts:
`(Invoke-JiraMethod -Method GET -URI 'http://<JIRAURL>/rest/tempo-accounts/1/account'`

Cheers!
