### ISSUE TITLE
Retrieve the key of a new-jiraissue

### ISSUE THREAD

**Issue by msacademy** [AtlassianPS/JiraPS#182]
If I create a new Jira issue, how can I return the key in case I want to do more updates to it with Set-jiraissue?

### Expected Behavior
If there was a returned value like standard output, it could be retrieved.  Then a script that is auto-generating an issue can send an email regarding the new issue being created along with the key or perform later set-jiraissue commands on the issue just created. 

### Current Behavior
new-jiraissue does not return any value that I can see as to the issue being created

### Possible Solution
Have an environment variable or powershell variable that gets filled after a new jira issue is created.  I could list all issues and look for the highest value but that could be inaccurate if two are created at the same time. 

### Steps to Reproduce (for bugs)
n/a

### Context
I have to use -fields for a new-jirassiue but the syntax for a plugin ID value does not not work.  For example, this works:

set-jiraissue ITSUP-5104 -fields @{customfield_11501 = "15"}

But this does not:

# create the issue with template data
$fields = @{
    Reporter = @{
    value = $reporter
    }
    'Priority' = @{
    name = $priority
    }
    customfield_12101 = @(@{
    value = $location
    })
    customfield_12100 = @(@{
    value = $pcilevel
    })
    customfield_11501 = @{
    value = $account_id}
    }

I tried id= and value = .  Error returned is:

set-jiraissue ITSUP-5104 -fields $fields
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [io.tempo.jira__account] - Can not deserialize instance of 
java.lang.Long out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1]
At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Internal\Invoke-JiraMethod.ps1:112 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError
 
So I was hoping to use the working syntax of the set-jiraissue command but I do not know the key that I would have just created.

### Your Environment
n/a

**Comment by lipkau** [comment]
I don't know about the type of `customfield_12100` and `customfield_12101`.
So not much I can say... but this should work (notice the quotes around `$account_id`):
```powershell
$fields = @{
  Reporter = @{
    value = $reporter
  }
  'Priority' = @{
    name = $priority
  }
  customfield_11501 = @{
    value = "$account_id"
  }
}
```

Regarding the other fields, here is the documentation I will use when writing our documentation on type of fields:
https://developer.atlassian.com/cloud/jira/service-desk/rest/#fieldformats

**Comment by msacademy** [comment]
Thanks for the attempt.  That syntax still did not work.  I will have to find another way.  Your other syntax works for the set-jiraussue, but I cannot find the right way (if it can be done) through -fields.


$fields = @{

Reporter = @{

value = $reporter

}

'Priority' = @{

name = $priority

}

customfield_12101 = @(@{

value = $location

})

customfield_12100 = @(@{

value = $pcilevel

})

customfield_11501 = @{

value = "$account_id"

}

}



PS C:\Windows\system32> set-jiraissue ITSUP-5104 -fields $fields
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [io.tempo.jira__account] - Can not deserialize instance of
java.lang.Long out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1]
At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.2.0.146\Internal\Invoke-JiraMethod.ps1:112 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError




The get-jirafield lists it as:


ID          : customfield_11501
Searchable  : True
Schema      : @{type=option2; custom=com.atlassian.plugins.atlassian-connect-plugin:io.tempo.jira__account;
              customId=11501}
Name        : Account
Custom      : True
Navigable   : True
Orderable   : True
ClauseNames : {Account, cf[11501]}



I am not sure how to tell the field type.  I can mouse over the value in the account to see the value of each account in the URL, though.  Here is all I see in the browser for one account.


[cid:9415d386-eecc-4bd7-971c-cd47ab4adec8]

And for "Humach" account, the URL comes back as:


https://bolderthinking.atlassian.net/plugins/servlet/ac/io.tempo.jira/tempo-accounts?user.key=randy.schmidt&project.key=ITSUP&project.id=13601&servicedesk.serviceDeskId=4&user.id=randy.schmidt#!/account/15/


Maybe this attribute/field cannot be done through PowerShell as it stands?


[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________

**Comment by lipkau** [comment]
The command is failing because a field is not in the correct format...
I am unable to help you with these:
```
customfield_12101 = @(@{
    value = $location
  })
  customfield_12100 = @(@{
    value = $pcilevel
  })
```
in order to find out what is the type of these, you can use `Get-JiraField customfield_12101`

**Comment by msacademy** [comment]
Got it.  Here is the proper syntax to update a plugin custom field (customfield_11501):


$fields = @{

Reporter = @{

value = $reporter

};

'Priority' = @{

name = $priority

};

customfield_12101 = @(@{

value = $location

});

customfield_12100 = @(@{

value = $pcilevel

});

customfield_11501 = "$account_id"

}


Thank you to everyone for your help.  This is a great tool for Jira users!!!!!




[Humach]

Randy Schmidt

Director of IT

wk: 641.243.8293 ext. 6625

www.humach.com<http://www.humach.com>



________________________________
