### ISSUE TITLE
Is it possible to add attachments to the issue and/or to an individual comment?

### ISSUE THREAD

**Issue by msacademy** [AtlassianPS/JiraPS#193]
I would like to add an attachment from another script to an issue, preferable to a comment line but if not at least to the issue itself.

### Expected Behavior
set-jiraissue -attachment "c:\temp\users.txt"

### Current Behavior
Do not see it in the doc.  An examination of the properties suggests it might be able to be done with -fields using an array

### Possible Solution
-fields ?

### Steps to Reproduce (for bugs)
n/a

### Context
Need to add attachments via PowerShell

**Comment by lipkau** [comment]
Attachments are not yet available. The feature request is in #137.
