### ISSUE TITLE
Add parameter for non-set operations in Set-JiraIssue

### ISSUE THREAD

**Issue by Zer010** [AtlassianPS/JiraPS#20]
If we take an issue and pipe it to Set-JiraIssue using the Fields parameter certain fields will throw errors as they do not support the 'set' operation. A good example is Comment.

Take:
```powershell
$fields = @{};
$fields.comment = "The insightful awesome comment I want to add!"
Get-JiraIssue -Key "Test01" | Set-JiraIssue -Fields $fields
```

The Result is of the code above yields: 
Resolve-JiraError : Jira encountered an error: [Field with id' comment' and name 'Comment' does not 
support operation 'set' Supported operation(s) are: 'add,edit,remove']

Currently in Set-JiraIssue:
```powershell
$issueProps.update.$id += @{
    'set' = $value;
}
```

The change I would propose, is to add a $FieldOperation. ParameterSet could be nice however that may pigeon hole other fields that don't conform. So it might be better off as an open string field. Thoughts?

```powershell
$operation = "$($FieldOperation)"
$issueProps.update.$id += @{
    $operation = $value;
}
```

All in all this module has been awesome, thank you for making it you are greatly appreciated!

**Comment by replicaJunction** [comment]
Hi! Sorry for the delayed response to this; I've had a lot of RL changes recently that have kept me busy.

I hadn't initially designed Set-JiraIssue to accept comments, as that was sort of the purpose of Add-JiraIssueComment, but your use case does make sense.

Are there a lot of fields that trigger this behavior, or is the comment field the primary one you've noticed? If that's the biggest offender, we may be able to add a handler specific to comments in the Fields hashtable.

Your idea for a FieldOperation parameter is a good one, but we'd have to have a way of associating a specific operation with a specific field - or just assume that all fields will use the same operation in a single call. That might take a bit more thought...perhaps a nested hashtable?

```powershell
$fields = @{
    comment = @{
        add = 'Another insightful comment'
    }
}

Get-JiraIssue -Key "Test01" | Set-JiraIssue -Fields $fields
```

**Comment by replicaJunction** [comment]
I still see the use in this feature, but I haven't figured out a good way to do so. I'm adding the "help wanted" tag to see if anyone else wants to chime in with some ideas.

**Comment by Zer010** [comment]
No worries. I was thinking of a child object something along the lines of PSJiraField that would be a hashtable containing the FieldName and ApiMethodType (Add, Edit, Update, etc). What I am debating is whether or not this becomes too brittle in the long term.

**Comment by lipkau** [comment]
@replicaJunction 
I see it as to cumbersome to handle comments in this command.
Making the fields has contain the operation add a new layer of complexity only for the comments to benefit from it.
Also, this only usecase this works well is adding a new comment. But that is not was `Set-` is supposed to do. It is supposed to be able to change the comment (edit).

I recommend adding a line to remove the comment element from the hash, if present and only allow for comments to be managed by dedicated functions.
