### ISSUE TITLE
"Invoke-JiraIssueTransition" appends error to ErrorVariable in case of successful result

### ISSUE THREAD

**Issue by arestarh** [AtlassianPS/JiraPS#209]
### Expected Behavior

"Invoke-JiraIssueTransition" should not append any error info to error variable if no error occurred.

### Current Behavior

"Invoke-JiraIssueTransition" appends error to ErrorVariable:
```powershell
$err=$null
Get-JiraIssue -Key 'IssueID'|Invoke-JiraIssueTransition -Transition '31' -ErrorVariable +err
$err
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.4.2\Internal\Invoke-JiraMethod.ps1:122 char:13
+         if (Get-Member -Name "Errors" -InputObject $result -ErrorActi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
```
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

> JirPS module version - 2.4.2
> Powershell version - 5.1.14409.1005

**Comment by lipkau** [comment]
This doesn't happen for other Cmdlets?

**Comment by arestarh** [comment]
Actually, I've noticed this behavior for mentioned cmdlet. Add-JiraIssueAttachment seems ok, New-JiraIssue seems ok to, Invoke-JiraIssueTransition is ok as well. Just like a few examples. Didn't check other cmdlets.

**Comment by lipkau** [comment]
You just contradicted the original description.
`Invoke-JiraIssueTransition` is ok or not?

**Comment by arestarh** [comment]
Sorry, my vad. I've edited previous comment.
