### ISSUE TITLE
Trouble with Set-JiraIssue

### ISSUE THREAD

**Issue by cjast** [AtlassianPS/JiraPS#211]
Not sure what I'm doing wrong. Importing a CSV with the values. Here is an example of the script.

`$Fields = @{'customfield_10412' = $_.AssignedTo;'customfield_10411' = $_.TV;'customfield_10415' = $_.OldID;'customfield_10408' = $_.Asset;'customfield_10401' = $_.Model;'customfield_10403' = $_.Manufacturer;'customfield_10404' = $_.Location; 'customfield_10405' = `$_.Station;}`

`$CSV | % {
    Set-JiraIssue -Issue $_.Key -Summary $_.Summary -Description $_.Description -Fields $Fields -Verbose
}`

```
Keeps returning this.
VERBOSE: GET https://jira..com/rest/api/latest/field with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
VERBOSE: Using saved Web session with username 
VERBOSE: GET https://jira..com/rest/api/latest/field with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
VERBOSE: Using saved Web session with username 
VERBOSE: GET https://jira..com/rest/api/latest/field with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
VERBOSE: Using saved Web session with username
VERBOSE: GET https://jira..com/rest/api/latest/field with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8

**Comment by lipkau** [comment]
Unfortunately you did not provide enough context of your script.

With only the information above, I can tell you the `$Fields` does not look like what you expect, as you are not yet using the CSV data.
Move that statement inside the `$CSV | % {`

**Comment by cjast** [comment]
I had actually tried that already. I pulled the Fields out and assigned them to a variable so it would be easier to try different formats.

The script below ends with the same results. It does not update any of the issues.
`$CSV | % {
    Set-JiraIssue -Issue $_.Key -Summary $_.Summary -Description $_.Description -Fields @{
        'customfield_10412' = $_.AssignedTo;
        'customfield_10411' = $_.TV;
        'customfield_10415' = $_.OldID;
        'customfield_10408' = $_.Asset;
        'customfield_10401' = $_.Model;
        'customfield_10403' = $_.Manufacturer;
        'customfield_10404' = $_.Location;
        'customfield_10405' = $_.Station;} -Verbose
}`

**Comment by lipkau** [comment]
Can you give the full console output (including -verbose)?

**Comment by cjast** [comment]
![untitled](https://user-images.githubusercontent.com/34755120/34361071-85277088-ea2c-11e7-8fab-d80ee7b604f7.png)

Here's a screenshot showing the output. One of the fields is a user field, and I believe that is what that error is complaining about.

**Comment by lipkau** [comment]
That's exactly the problem. Here is a snip of how you set a user:

```
Fields = @{ Assignee = @{ name = (Get-JiraSession).UserName } }
```

**Comment by cjast** [comment]
Yep that corrected the issue. 

Just to make sure I am understanding correctly, for my specific use case, it would be 
`Fields = @{'customfield_10411' = @{ name = (get-jirasession).$_.AssignedTo}}`

**Comment by lipkau** [comment]
no.
`(Get-JiraSession).UserName` is my way of identifying the user that is logged in.

As you are using the info from the CSV, this would suffice:
```powershell
Fields = @{'customfield_10411' = @{ name = $_.AssignedTo}}
```
