### ISSUE TITLE
Problem using custom ConfigFile of Set/Get-JiraConfigServer

### ISSUE THREAD

**Issue by S9uare** [AtlassianPS/JiraPS#212]
When using a custom config file, i found that it's possible to SET the server. however the other functions fail.

```
# This works
Set-JiraConfigServer -Server $myJiraServer -ConfigFile $myConfigFilePath
# This fails
New-JiraSession -Credential $myCred
# This fails too
New-JiraSession -Credential $myCred -ConfigFile $myConfigFilePath

# This works
$Global:ConfigFile = $myConfigFilePath
New-JiraSession -Credential $myCred
```

### Expected Behavior

Did not expect to use a global scope variable for 1 single module function

#### Error of `New-JiraSession -Credential $myCred`
```
Config file [C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.4.4\config.xml] does not exist. Use Set-JiraConfigServer first to define the configuration file.
```

#### Error of `New-JiraSession -Credential $myCred -ConfigFile $myConfigFilePath`
```
New-JiraSession : A parameter cannot be found that matches parameter name 'ConfigFile'.
```

### Possible Solution

Storing JiraServer config in module's PrivateData
Adding `ConfigFile` parameter to all functions that use `Get-JiraConfigServer`

**Comment by lipkau** [comment]
Currently, this module tries to save the `config.xml` file in the path where the module was installed.
( This will be changed with #194 )

The problem you are facing is a result of the module being installed as admin (in a path where the current user has no write permissions (to write the `config.xml` file) without elevation).
You can solve this by:
* installing the module with `Install-Module JiraPS -Scope CurrentUser`
* running the powershell session as admin
