### ISSUE TITLE
Add-JiraIssueComment can't leave comments on tickets in Jira Service Desk

### ISSUE THREAD

**Issue by JoeJe1993** [AtlassianPS/JiraPS#213]
### Expected Behavior
On an existing Jira Service Desk ticket, Add-JiraIssueComment should be able to leave a comment.

### Current Behavior

When executing Add-JiraIssueComment:

![image](https://user-images.githubusercontent.com/29064065/35384098-24db58dc-01bc-11e8-8e98-0a935e52006f.png)

No comment left:

![image](https://user-images.githubusercontent.com/29064065/35384258-a0c0f420-01bc-11e8-856c-dfb4f0ff7f48.png)

### Your Environment

![image](https://user-images.githubusercontent.com/29064065/35384296-bde66a76-01bc-11e8-8436-73263f676cdc.png)
![image](https://user-images.githubusercontent.com/29064065/35384361-f207969a-01bc-11e8-91eb-b91e876bb002.png)

**Comment by JoeJe1993** [comment]
I have just updated JiraPS and I'm still getting the same problem:

![image](https://user-images.githubusercontent.com/29064065/35384655-edb8f27c-01bd-11e8-8a72-56090aaffe44.png)

**Comment by JoeJe1993** [comment]
Strange behaviour: Our Jira Slack plugin is picking up the comments I'm trying to make.

![image](https://user-images.githubusercontent.com/29064065/35384871-8f5aade6-01be-11e8-9c2c-8e668a00b593.png)

**Comment by lipkau** [comment]
1. In the screen of the web UI of the issue, can you select the "Comments" tab?
2. what happens when you open the "RestUrl" of the object powershell is returning?

**Comment by JoeJe1993** [comment]
![image](https://user-images.githubusercontent.com/29064065/35388479-e3612066-01cb-11e8-9465-c19a91b06bd5.png)

![image](https://user-images.githubusercontent.com/29064065/35388515-066f517c-01cc-11e8-946f-32a410a73d31.png)

**Comment by lipkau** [comment]
It appears to me that the Service Desk is not showing some kind of comments.
So the comment is there - was created successfully.
now the question is... what is happening...

did you create the comment with 2.2 or 2.4?
2.3 changes the default visibility of comments:
https://github.com/AtlassianPS/JiraPS/releases/tag/v2.3.160

**Comment by JoeJe1993** [comment]
I don't see -AddComment appearing on Set-JiraIssue. After updating, I did Remove-Module JiraPS and then Import-Module JiaPS.

![image](https://user-images.githubusercontent.com/29064065/35392384-9591f730-01d9-11e8-8436-eba2869f8831.png)

**Comment by lipkau** [comment]
`Add-JiraIsssueComment -Issue ABC-1234 -Comment "hello there" -VisibleRole "All Users"`
