### ISSUE TITLE
Get-JiraProject to sholl all projects does not extract content of available fields

### ISSUE THREAD

**Issue by dernorberto** [AtlassianPS/JiraPS#216]
### Expected Behavior
If I run 

> Get-JiraProject -credential $cred| fl id,category,issuetypes,resturl,key,components,name,description,roles

or

> Get-JiraProject -credential $cred

... I should see ALL the fields
1. ID         
1. Category   
1. IssueTypes 
1. RestUrl    
1. Key        
1. Components 
1. Name       
1. Description
1. Roles      

### Current Behavior
running:
> Get-JiraProject -credential $cred| fl id,category,issuetypes,resturl,key,components,name,description,roles

or 

> Get-JiraProject -credential $cred

does not show the fields:
1. IssueTypes 
2. Components 
3. Description
4. Roles    

### Possible Solution
Allow to show all fields with a project list query

### Steps to Reproduce (for bugs)
1. run: Get-JiraProject -credential $cred| fl IssueTypes,Components,Description,Roles    
2. output will show empty fields

### Context
* we are archiving projects by changing permissions scheme and we also add "ARCHIVED" to the description
* this would help to at least quickly list all projects that are meant to be archived

### Your Environment
* JIRA Cloud
* latest JiraPS
```Get-Module JiraPS -ListAvailable | select version

Version
-------
2.4.4
```

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lipkau** [comment]
The reason for this is the lack of the `?expand=` parameter in the code when requesting all the projects.
I will fix this with #215
