### ISSUE TITLE
summary ~ cannot be used in query HTTP error 400 - BadRequest

### ISSUE THREAD

**Issue by Eagleman7** [AtlassianPS/JiraPS#218]
On version 2.4.4 of JiraPS on Windows Server 2008R2 I cannot use the summary ~ query, it returns error 400.

summary ~ can be used on the advanced filter on Jira itself. 

This message is shown when executing the following command: 
`Get-JiraIssue -Credential $cred -Query 'summary ~ "Bart" '`

`WARNING: JIRA returned HTTP error 400 - BadRequest`

**Comment by lipkau** [comment]
I am sorry to say, I am unable to reproduce this.
I tested on a cloud server and a on-premise.

Here is what I get:

```powershell
I ♥ PS>Get-JiraIssue -Credential $cred -Query 'summary ~ "Test" '

Key              Summary                                                  Status                   Created
---              -------                                                  ------                   -------
CSD-3            This is a test                                           Open                     2017-09-26 08:54:12
```

please provide more information about your environment:
> ```posh
> Get-Module JiraPS -ListAvailable | select version
> $PSVersionTable
> ```

**Comment by Eagleman7** [comment]
PS C:\Windows\system32> Get-JiraIssue -Credential $cred -Query 'summary ~ "Test" '
WARNING: JIRA returned HTTP error 400 - BadRequest
PS C:\Windows\system32> Get-Module JiraPS -ListAvailable | select version

Version
-------
2.4.4


PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lipkau** [comment]
Does any other command (eg `Get-JiraProject`) work with that `-Credential $cred`?

**Comment by Eagleman7** [comment]
Yes, for example this command works:

Get-JiraIssue -Credential $cred -Query 'labels = PowershellAD AND status in (Open, "To Do", "Waiting for customer", "Waiting for support")'

**Comment by lipkau** [comment]
All I can find in the [documentation](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/search-search) is this:

> **STATUS 400**: Returned if there is a problem with the JQL query.

I imagine you tried the exact same filter, with exact the same user in the jira web UI, right?

**Comment by Eagleman7** [comment]
![image](https://user-images.githubusercontent.com/4787591/37517106-a7629bfa-2910-11e8-9a7c-0e650ff765a3.png)

Seems to be working in the web interface?

**Comment by lipkau** [comment]
I ran it against my cloud server and got this:
![image](https://user-images.githubusercontent.com/4992870/37518194-7077ead8-2914-11e8-867c-761b3258f2a6.png)

Can you reproduce these steps and share the results?

**Comment by Eagleman7** [comment]
Issue was resolved, was using this to login:

$secure = get-content cred.txt | convertto-securestring

But was missing the $cred variable, found this out when debugging.

$cred = New-Object System.Management.Automation.PSCredential ("servicedeskapi@company.net", $secure)
