### ISSUE TITLE
New-JiraIssue uses magic $ConfigFile variable

### ISSUE THREAD

**Issue by KevinMarquette** [AtlassianPS/JiraPS#219]
https://github.com/AtlassianPS/JiraPS/blob/1cdc0cbf08ef9b8056ceef839985d78768b4cc0e/JiraPS/Public/New-JiraIssue.ps1#L83

As I was debugging another issue and `$ConfigFile` was `$null` in my debugging session. I don't know if that was just an artifact of VSCode, but this variable looks out of place. It is not defined in this function but is being used within it.  

If I had to guess, `$ConfigFile` was a parameter but was removed. I think you handle the null value down the stack, so this is just more of a code cleanup thing.

**Comment by lipkau** [comment]
Hey.

Yes; it was a parameter.
It has been removed a long time ago... 
This was already "fixed" in pr #215 and will be merged for the next minor release

**Comment by KevinMarquette** [comment]
Thank you. Sorry, I should have checked the other branches.

**Comment by lipkau** [comment]
No sweat.
But I am glad to hear you are using this module :-)
