### ISSUE TITLE
JiraPS vs PSJira - clarity needed

### ISSUE THREAD

**Issue by mwoffenden** [AtlassianPS/JiraPS#235]
I have both of these installed in my Visual Studio environment.

**JiraPS** has 63 commands and looks like this:

<img width="241" alt="screenshot_1351" src="https://user-images.githubusercontent.com/6774346/39085647-b638b0f6-4553-11e8-9031-0433b79b118e.png">

On the other hand **PSJira** looks like the following.

<img width="235" alt="screenshot_1352" src="https://user-images.githubusercontent.com/6774346/39085653-dc52508a-4553-11e8-867a-628f0800616f.png">

Can I get some clarity on this please?

**Comment by lipkau** [comment]
What clarity would you expect?

* the version of `PSJira` is `> 2`, while `JiraPS` is `=< 2`
* when loading the `PSJira` module, you get a warning telling you "this module is no longer supported"

**Comment by lipkau** [comment]
My response what not meant to clarify; but to inquire where you would expect such an information.

* you are browsing `https://github.com/AtlassianPS/JiraPS/issues`. This should already tell you the name of the "correct" module
* when you load the "incorrect" module, you will be told so
* when visiting the "old" repository, the title already states `[deprecated]` in it's title
* all github project point to the https://atlassianps.org homepage... where all current versions and latest documentations are linked.

So, again, please tell me **where** you would have expected the information you are lacking to be.

**Comment by mwoffenden** [comment]
Your first three bullets are not helpful but the last one at least gives me a starting point.
