### ISSUE TITLE
How do I add a label to a customfield without deleting the old ones

### ISSUE THREAD

**Issue by derChristoph** [AtlassianPS/JiraPS#243]
I have a customfield:
ID          : customfield_15505
Searchable  : True
Schema      : @{type=array; items=string; 
              custom=com.atlassian.jira.plugin.system.customfieldtypes:labels; customId=15505}
Name        : BuildID
Custom      : True
Navigable   : True
Orderable   : True
ClauseNames : {cf[15505], BuildID}

With this code i can set the Label:

$parameters = @{
    Fields = @{
        customfield_15505 = @( "ValueOfTheLabel" )
    }
}
Set-JiraIssue @parameters -Issue WAWI-2448

### Expected Behavior
But i want add say: ValueOfTheLabel2 an keep ValueOfTheLabel, how do i do this?

### Possible Solution
I have no ideas how to implement this

### Context
I want my Jenkins to put the BuildID in the Ticket, it is possible that one ticket runs manny times, and i'd like to keep track of the BuildID's a ticket went trou.

### Your Environment
Get-Module JiraPS -ListAvailable | select version

Version
-------
2.5.14

**Comment by lipkau** [comment]
this should do the trick:

```powershell
[array]$labels = (Get-JiraIssue WAWI-2448).customfield_15505

$labels += "ValueOfTheLabel"
$parameters = @{
    Fields = @{
        customfield_15505 = $labels
    }
}
Set-JiraIssue @parameters -Issue WAWI-2448
```

**Comment by derChristoph** [comment]
You are my Hero!
