### ISSUE TITLE
 Get-JiraUser -IncludeInactive -UserName '%' returns only 1 user

### ISSUE THREAD

**Issue by janegilring** [AtlassianPS/JiraPS#246]
### Expected Behavior
 Get-JiraUser -IncludeInactive -UserName '%' should retrieve all users.

### Current Behavior
 Get-JiraUser -IncludeInactive -UserName '%' returns only 1 user.

### Steps to Reproduce (for bugs)

1. $AtlassianCredential = Get-Credential
2. Set-JiraConfigServer -Server 'https://tenant.atlassian.net'
3. Get-JiraUser -IncludeInactive -UserName '%'
4. New-JiraSession -Credential $AtlassianCredential
5. Get-JiraUser -IncludeInactive -UserName '%'

### Context
Return all users from the Atlassian tenant

### Your Environment
`2.5.17                                                                                                  
PSVersion                      5.1.14393.2155     
`

**Comment by lipkau** [comment]
Thank you for reporting this, Jan.

As my on-premise server is configured not to return results for wildcards, I never tested this.

**Comment by janegilring** [comment]
I just tried to re-run Get-JiraUser -IncludeInactive -UserName '%' after upgrading to JiraPS 2.7.0.
Now I get more than one user returned.
However, there are 550 users registered when looking via the admin webpage, but only 50 is returned by Get-JiraUser.

Are there any paging or similar which needs to be implemented in order to return all users?

**Comment by lipkau** [comment]
You are right.
It is not a paginated response, but the default limits the # of results to 50.

Can you please test it on this branch?
https://github.com/lipkau/JiraPS/tree/fix/ParameterForMaxResultsOfUsers

I am unable to do so, as I have no system with >50 users where I have permissions to enumerate all users

**Comment by janegilring** [comment]
When running Get-JiraUser -IncludeInactive -UserName '%' -MaxResults 900 all users is returned, thanks a lot!

The command takes quite a while to run, but that's not an issue in our scenario (licensing/reporting).

**Comment by lipkau** [comment]
Great to hear that.
I will publish that branch with the next minor update (could be a couple of weeks)

That API does not allow for paging. So the only think that can be done (that occurs to me) is to filter for `a%` then `b%` aso and run them in parallel
