### ISSUE TITLE
Set-JiraConfigServer failes when there are no `/` in the server name

### ISSUE THREAD

**Issue by michalporeba** [AtlassianPS/JiraPS#332]
## Description

When value of the server doesn't have `/` in the name an exception is thrown. 

## Steps To Reproduce

![image](https://user-images.githubusercontent.com/120880/51460886-9671a780-1d54-11e9-8ab8-704b565041b5.png)

## Your Environment

```
PS C:\> Get-Module JiraPS -ListAvailable | Select Name, Version

Name   Version
----   -------
JiraPS 2.9.0
JiraPS 2.8.6
```

**Comment by lipkau** [comment]
Hi.

This is working correctly.
The reason why it is not working, is because you did not provide the schema of the url.
If you add the `https://`, it should work fine

**Comment by lipkau** [comment]
Please reopen if the problem was not resolved

**Comment by michalporeba** [comment]
I think it would be a nice to have not to have to specify the schema, but if that's what it needs then it resolves my problem. Thank you.

**Comment by michalporeba** [comment]
You could review the string and if it doesn't start with schema simply
prepend it with https:// for example. Another step could be to try if it
works and if not try http:// before returning an error.

**Comment by lipkau** [comment]
> Another step could be to try if it works and if not try http:// before returning an error.

*definitely not!* the module uses basic auth to authenticate. in an http connection, the credentials can be read.
Ideally, I would remove support for non-tls secured connections. but for now I have only placed this in the documentation

> You could review the string and if it doesn't start with schema simply prepend it with https:// for example.

That's what the screenshot shows, but using the `[URI]` class. This allows me not the have to validate the format of the string
