### ISSUE TITLE
Possibility to add custom worklog attributes to New-JiraIssueWorklog

### ISSUE THREAD

**Issue by RyoukoKonpaku** [AtlassianPS/JiraPS#345]
## Context
Our company uses a number of [custom worklog attributes](https://tempoplugin.jira.com/wiki/spaces/TEMPO/pages/232914960/Configuring+worklog+attributes) when submitting worklogs for the day. I wanted to automate worklog submission so I can submit in bulk in times when needed. 

Currently `Add-JiraIssueWorklog` cmdlet doesn't have a parameter to add additional worklog attributes, so after submitting a bunch of worklogs from a custom script, I have to update each one with their respective custom worklog fields on tempo. 

## Description
Add support for submitting custom worklog attributes to the `Add-JiraIssueWorklog` cmdlet. Possibly an additional parameter `-WorkLogAttributes $PSObject / $SomeIdentifierForTheWorkLog`.

## Additional Information
I don't have a clear idea yet as to what identifier is appropriate for getting the custom attributes, so maybe an additional `Get-JiraWorkLogAttributes` might be needed which returns the needed object. But maybe a better solution can is available.

**Comment by alexsuslin** [comment]
Are you sure, you're reffering to worklog attribute (like tempo plugin allows to do) or it is just jira issue custom field, that is laying on the screen during the resolve issue porcess, where you can add worklog (Time Tracking Field)

**Comment by RyoukoKonpaku** [comment]
Now that you mentioned that, after re-checking. It seems that might be the case here. 

I guess it's out of scope for the Module? It seems to be part of a plugin for tempo and not Jira itself. If it's out of scope I can close the issue, It seems they also have a REST API available so a custom script for updating might suffice for my requirements. Thanks for the heads up.

**Comment by lipkau** [comment]
The API for the worklog does not support any additional attributes.
Therefore, this request can't be fulfilled without running `Set-JiraIssue` after the change.
