### ISSUE TITLE
Fix Provided: Get-JiraUser function inside Invoke-JiraIssueTransition function can return an array of users

### ISSUE THREAD

**Issue by mirrorgleam** [AtlassianPS/JiraPS#349]
## Description

If JIRA has usernames such as "jsmith", "jsmithy", "jsmith1", "jsmithson" and you are trying to assign the ticket to "jsmith" it will fail because the assignee field needs a string but this function is returning an array of strings.

## Steps To Reproduce
```powershell
$userDetails = Get-JiraUser -UserName "jsmith" -Credential $jiraCredentials -Exact
Invoke-JiraIssueTransition -Issue "TCKT-1234" -Credential $jiraCredentials -Transition 1 -Assignee $userDetails 
```
## Expected behavior

Ticket will be assigned to the user in $userDetails

## Possible Solution

My Fix:	Modified JiraPS.psm1 
line 2964: `if ($assigneeObj = Get-JiraUser -InputObject $Assignee -Credential $Credentials) {`
change:	added `-Exact` flag to `Get-JiraUser` function

In https://github.com/AtlassianPS/JiraPS/blob/master/JiraPS/Public/Invoke-JiraIssueTransition.ps1 
line 112

**Comment by alexsuslin** [comment]
Could you please submit a pull request to this issue?

**Comment by mirrorgleam** [comment]
I'm not familiar with pull requests but I'll look it up and try to figure out what I need to do.

**Comment by lipkau** [comment]
Thank you, @mirrorgleam .
Here are the instructions on how to submit a Pull Request:
https://atlassianps.org/docs/Contributing/#how-to-submit-code-changes

of course I would gladly support you with it :-)

**Comment by mirrorgleam** [comment]
Just submitted it. I hope it's up to standards.
I just submitted one for the Invoke-JiraIssueTransition, should I also submit one for the JiraPS.psm1 file?

**Comment by mirrorgleam** [comment]
And on further review I now see that isn't necessary.
Clever coding on that file. I've learned something new about PS.
Also, thanks for building this module. It's been extremely helpful these past few months.

**Comment by lipkau** [comment]
I do not see your PR yet.
https://github.com/AtlassianPS/JiraPS/pulls

can you post the link to the PR you created?

**Comment by lipkau** [comment]
I see your commit:
https://github.com/mirrorgleam/JiraPS/commit/0a201610313d582d6effb2eb7082b2c21ae27a63

By clicking this button, you create the PR:
![image](https://user-images.githubusercontent.com/4992870/56810706-41ec3580-6837-11e9-99b5-1f62fef6aae8.png)

This is what you should get:
https://github.com/AtlassianPS/JiraPS/compare/master...mirrorgleam:mirrorgleam-patch-1?expand=1

**Comment by mirrorgleam** [comment]
This is what I get when I click that.
![image](https://user-images.githubusercontent.com/8442093/56811541-f02bb700-6806-11e9-8728-241d84c2aa37.png)

**Comment by mirrorgleam** [comment]
AH THINK I FOUND IT :D

**Comment by mirrorgleam** [comment]
It looks like it's in your pull requests now
