### ISSUE TITLE
New-JiraIssue with issue security

### ISSUE THREAD

**Issue by PFS-IT** [AtlassianPS/JiraPS#352]
## Description

I want to create a new JIRA issue and set the issue security

## Steps To Reproduce

What I've tried so far.

```
$Fields = @{
	description = "Test"
	duedate = "2019-05-11"	
	security = @{ id = 11213 }
}
```

```
$Fields = @{
	description = "Test"
	duedate = "2019-05-11"	
	security = { id = 11213 }
}
```

```
$Fields = @{
	description = "Test"
	duedate = "2019-05-11"	
	security = 11213
}
```

All fail with the following error.

Could not find a valid ID in the security object.

![grafik](https://user-images.githubusercontent.com/50320834/57217978-6a70ee00-6ff4-11e9-90c7-6769afa9717d.png)

My command:

```powershell
New-JiraIssue -Project "BIT" -IssueType "Aufgabe" -Summary "Test Issue" -Fields $Fields -Reporter "Me"
```

Getting rid of the security ID works!

## Expected behavior

The issue gets created and the security is set.

## Screenshots

See above.

## Your Environment

JiraPS: 2.10.3
PowerShell: 4
Jira Core 8.0.1

**Comment by lipkau** [comment]
what do you get as the output for 
```powershell
(Get-JiraIssueCreateMetadata -Project BIT -IssueType Aufgabe | ? id -eq security).AllowedValues
```
?

**Comment by PFS-IT** [comment]
Here's the output.

![grafik](https://user-images.githubusercontent.com/50320834/57283010-7e792600-70ae-11e9-89df-435a85f5a2bd.png)

**Comment by lipkau** [comment]
I was unable to set up my environment to reproduce this.
According to the [documentation](https://docs.atlassian.com/software/jira/docs/api/REST/8.1.0/#api/2/issue-createIssue), this code of yours should have worked:
```
$Fields = @{
	description = "Test"
	duedate = "2019-05-11"	
	security = @{ id = 11213 }
}
```

Please run this:
```powershell
New-JiraIssue -Project "BIT" -IssueType "Aufgabe" -Summary "Test Issue" -Fields $Fields -Reporter "Me" -debug
```

and on the message 
> ```DEBUG: [Invoke-JiraMethod] Invoke-WebRequest with $splatParameters:```
enter the suspend and inspect `$body`

**Comment by PFS-IT** [comment]
Hey everyone
I found a work-around by using the default cmdlet Invoke-WebRequest. Since it seems to work as expected within your environment, I propose we close this issue.
Thanks either way for your help!
