### ISSUE TITLE
Feature: Enable / disable user

### ISSUE THREAD

**Issue by replicaJunction** [AtlassianPS/JiraPS#376]
## Context

> **Is your feature request related to a problem? Please describe.**

Way back in #1, I mentioned that it was not possible to set users as active vs. inactive via the REST API. To my surprise, [the Atlassian issue I've been tracking for years](https://jira.atlassian.com/browse/JRASERVER-37294) has been updated, and they've finally added support for this in JIRA 8.3.0.

Since it is now possible to manage this via REST, we should add support for it in this project.

## Description

> **Describe the solution you'd like**

* Add a new parameter for Set-JiraUser: `-Enabled [bool]`
* If the parameter is provided, add `active: [true | false]` to the body of the REST endpoint
* If the parameter is not provided, do not change the user's active state

## Additional Information

Atlassian's doc on the [user endpoint](https://docs.atlassian.com/software/jira/docs/api/REST/8.3.0/#api/2/user-updateUser) contains the `active` property.

I have not tested this myself, as I don't have access to a new enough JIRA environment to play with.

I don't recommend doing a check of the JIRA server version before trying to set this property, as that would negatively impact performance. Instead, this would just be a "user beware" feature that is marked in the documentation as not usable on versions of JIRA older than 8.3.0.

This should also be a pretty simple change for anyone looking to get their feet wet contributing to the project.

**Comment by lipkau** [comment]
excellent contribution. thank you.
I am looking forward to your future contributions.
xD

> I don't have access to a new enough JIRA environment to play with.
Lies! you have access to powershell.atlassian.net ;-)

**Comment by johnheusinger** [comment]
Since the API and Jira web interface refer to active/inactive language rather than enabled/disabled, what are your thoughts on naming the parameter -Active rather than -Enabled?

In any case I'd like to take care of this issue :smile:
