### ISSUE TITLE
New-JiraCustomer and Remove-JiraCustomer commands needed

### ISSUE THREAD

**Issue by BigHouseITGuy** [AtlassianPS/JiraPS#379]
## Context

We're moving to Jira Service Desk and I'd like to 1) pre-populate our organization's customers (we're an internal service department, so our "customers" are our company's employees) and, 2) update the customers in the future (add new, remove old).

## Description

New-JiraCustomer commandlet with switches for
- Organization Name
- Customer Name
- Customer Email

Remove-JiraCustomer with switches for
- Customer Name
- Customer Email

## Additional Information

REST API for Customers already exists (/servicedeskapi/customer) and is [no longer experimental](https://developer.atlassian.com/cloud/jira/service-desk/#recent-changes). 

Customer upload script using the experimental API was written here: https://github.com/iokiwi/jsd-bulk-customer-upload

**Comment by lipkau** [comment]
Hello @BigHouseITGuy 

Jira Service Desk is not part of this module.
Just like Jira Agile (the scrum and kanban boards), a new module (`JiraAgilePS` and `JiraServiceDeskPS`) could extend the functionality of `JiraPS`.
However, I currently do not have the time for writing such a module.
_if someone is interested in writing this, I am more than willing to create the setup (repository, CI, CD, PSGallery, etc)_

**Comment by lipkau** [comment]
but you can use the `Invoke-JiraMethod` from `JiraPS` to write your own function. something like

```powershell
Import-Module JiraPS
Set-JiraConfigServer "https://….."

# your code
Invoke-JiraMethod -Uri "$(Get-JiraConfigServer)/rest/servicedeskapi/customer" -Method POST -Body (@{
  "displayName" = "Fred F. User"
  "email" = "fred@example.com"
} | ConvertTo-Json)
# your code
```

**Comment by BigHouseITGuy** [comment]
Thank you!
