### ISSUE TITLE
How To set time tracking with New-JiraIssue correctly?

### ISSUE THREAD

**Issue by sonadorixx** [AtlassianPS/JiraPS#386]
I've read the documentation so far, but im not able to set the time tracking when creating a new issue.

at the moment i try this. 

```powershell
$parameters  = @{
                project = $item.Node.projectKey
                summary = $item.Node.summary
                description = $item.Node.description
                issueType = $item.Node.issueType
                Priority = if ($item.Node.priority -eq "Showstopper") {'10000'} else {'10201'}
                Reporter = $User
                Fields = @{
                    components = @(
                        @{ name = $item.Node.components.component }
                    )
                    customfield_10606 = $startTime
                    timetracking = @(
                        @{originalEstimate = $item.Node.estimatedDuration }
                        @{remainingEstimate = $item.Node.estimatedDuration }
                    )
                    customfield_10607 = $endTime
                    fixVersions = @(
                        @{ name = $release }
                    )
}
$IssueCreation = New-JiraIssue @parameters
```

But this is causing an error:

> Can not deserialize instance of com.atlassian.jira.issue.fields.rest.json.beans.TimeTrackingJsonBean...

Any hint how to solve this?

**Comment by sonadorixx** [comment]
I solved it by "unwrapping" the parameters hashtable and filling it manually

 

> $parameters  = @{}

> $componentsArray = @()
            Foreach ($component in  $item.components.component) {
                $componentHashtable = @{} 
                $componentHashtable.Add("name", $component)
                $componentsArray += $componentHashtable
            }
            $componentsArray += $componentHashtable
            $fields = @{}
            $fields.components = $componentsArray

        later

> $parameters.Fields = $fields

**Comment by lipkau** [comment]
This is the correct format:

```
Fields = @{
        timetracking = @{
            originalEstimate = "10d"
            remainingEstimate = "1d"
        }
    }
```

**Comment by sonadorixx** [comment]
Works :)
