### ISSUE TITLE
Add support for FixVersions field in Set-JiraIssue

### ISSUE THREAD

**Issue by replicaJunction** [AtlassianPS/JiraPS#40]
Currently, you can change an existing Fix Version field like this:

``` powershell
Set-JiraIssue TEST-01 -Fields @{
    'fixVersions'=@(
        @{
            name='MyFixedVersion'
        }
    )
}
```

Or for a more variable method:

```
$VersionHash = @{"name" = "MyFixedVersion"}
$VersionArray = @($VersionHash)
$field = @{"fixVersions" = $VersionArray}
Set-JiraIssue -Fields $field
```

It would be nice to add a param to Set-JiraIssue to encapsulate this a bit.

Also, potentially providing support for adding fix versions when they don't already exist.

**Comment by replicaJunction** [comment]
The "fixVersions" string is case-sensitive:

https://answers.atlassian.com/questions/14200536/how-to-create-an-issue-with-a-fix-versions-value-using-the-rest-api

**Comment by replicaJunction** [comment]
Better example, with exact JSON syntax:

https://answers.atlassian.com/questions/47904/answers/30945696

**Comment by replicaJunction** [comment]
Added the function to that commit. I'm still getting my test JIRA instance configured, and I'm still getting errors that the "fixVersions" field isn't on the proper screen. I'll merge these changes back to master as soon as I can verify that they're actually working.

**Comment by midwan** [comment]
If we can also add the new version name (if it doesn't exist) it would be great. Looking forward to this one.

**Comment by lipkau** [comment]
I think it would be best to split the creation of new `fixVersions` into a function of it's own.
Creating new *Versions* is only allowed for Admins.
Mixing admin activities in a function you are not required to be an Admin sounds misleading to me.

Unless this is controlled with a `[switch]`.
But I would still prefer a function (`New-JiraVersion`) that returns `false` if the Version already exists.

By doing this, you can also populate the other fields of a *Version* _(Description, Start date and Release date)_

`New-JiraVersion @('MyFix', 'SomeoneElsesFix') | SetJiraIssue Test-01`

**Comment by replicaJunction** [comment]
I'd agree with that - it makes more sense to manage versions with a separate set of functions.

Can anyone take a look at the issue-40 branch and verify that the -FixVersion parameter works properly?

**Comment by Izonite** [comment]
Hi, 
I'm not a very skilled PS developper and I'm quite a noob with GIT but if that helps, I'm making some cmdlets to manage components and versions... That seems to do the job for now, but I still need to build some missing the Pester tests.
I pushed these cmdlets today, if someone wants to have a look :)
[https://github.com/Izonite/PSJira/commit/efa8d4fd3f78ae4939733020a3c3523b320f0ee8](url)

**Comment by Dejulia489** [comment]
Please assign this issue to me, this will be resolved with PR 106.
