### ISSUE TITLE
Cannot get or set assignee of issues

### ISSUE THREAD

**Issue by Growlert** [AtlassianPS/JiraPS#404]
## Description

Seems like something is broken on the Jira side yesterday. I'm not able anymore to get issue assignee by name or set it, the property "name" of assignee is now empty.

## Steps To Reproduce

`(Get-JiraIssue "issue_key").assignee.name` returns nothing
`Set-JiraIssue -Issue "issue_key" -Assignee "user_name"` returns no error, but nothing assigned

## Expected behavior

Should work as expected

## Your Environment

> ```powershell
> Get-Module JiraPS -ListAvailable | Select Name, Version
> $PSVersionTable
> ```

**Comment by rschmidt2** [comment]
I have the same issue using Get-JiraIssue -Query "project in (ITHD) AND status != Closed AND status != Resolved AND status != Done AND status != Canceled ) ORDER BY assignee, priority DESC, updated DESC" | select key, assignee, duedate, updated, created, summary, components.  This is in a daily email script that just started acting up on Feb 13th.

**Comment by mattiaswolff** [comment]
We the exactly the same issue..

```
PS J:\Powershell\Functions> Get-Module JiraPS -ListAvailable | Select Name, Version

Name   Version
----   -------
JiraPS 2.12.5
JiraPS 2.9.0


PS J:\Powershell\Functions> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by nathan-aung** [comment]
yea, same issue here.

 Get-Module JiraPS -ListAvailable | Select Name, Version

Name   Version
----   -------
JiraPS 2.12.5 
JiraPS 2.9.0

**Comment by rizickus** [comment]
Same here!
```
JiraPS 2.12.5

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```

**Comment by lipkau** [comment]
The changes in the api of the cloud are not that trivial.
And to make matter worse, the changes do not apply to jira server.
[Deprecation notice and migration guide for major changes to Jira Cloud REST APIs to improve user privacy](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide)

I got a few things working again. But it's not yet finished:
https://github.com/lipkau/JiraPS/commit/a8a31883bacb4efee0657976c71b9d560b0ae41d

**Comment by LaurentGoderre** [comment]
In the case of creating a new issue the line that fails is here:

https://github.com/AtlassianPS/JiraPS/blob/master/JiraPS/Public/New-JiraIssue.ps1#L100

Can it become somethign like:

```Powershell
$user=$(Get-JiraUser -Credential $Credentia)
If ([string]::IsNullOrEmpty($user.Name)) {
  $requestBody["reporter"] = @{"id" = "$user.AccountId"}
} Else {
  $requestBody["reporter"] = @{"name" = "$user.Name"}
}
```

**Comment by vyacheslav-shcherbak-globallogic-com** [comment]
Get-JiraUser returns blank Name for all users. Please fix it ASAP.

**Comment by LaurentGoderre** [comment]
@vyacheslav-shcherbak-globallogic-com I don't think that will happen, JIRA remove that field from the API. This is just a wrapper for the API.

**Comment by vyacheslav-shcherbak-globallogic-com** [comment]
> @vyacheslav-shcherbak-globallogic-com I don't think that will happen, JIRA remove that field from the API. This is just a wrapper for the API.

Will it possible to reassign a Jira issue to an another user  in another way while this functionality does not work? When are you going to fix it?
Can somebody to rewrite this to use AccountId instead of Name, eg.

`Set-JiraIssue -Issue $IssueKey -Assignee (Get-JiraUser -UserName "$($UserName)").AccountId -Credential $Cred
`
instead of this

`Set-JiraIssue -Issue $IssueKey -Assignee (Get-JiraUser -UserName "$($UserName)") -Credential $Cred`

**Comment by Growlert** [comment]
> Set-JiraIssue -Issue $IssueKey -Assignee (Get-JiraUser -UserName "$($UserName)").AccountId -Credential $Cred> 
Not working. It throws me the error:
_Invoke-JiraMethod : Specified user does not exist or you do not have required permissions_

**Comment by BigHouseITGuy** [comment]
For those of you looking for a workaround, I think this will do the trick:

```
$assignTo = "BigHouseITGuy"

$jiraUserData = get-jirauser -UserName $assignTo -exact | Select-Object *

$accountIdObject = [pscustomobject]@{
    accountId = $jiraUserData.accountId
}

$fields = @{
    'assignee' = $accountIdObject
}

Set-JiraIssue -Issue $issue.key -Fields $fields

```

This also works for reporter.

**Comment by Growlert** [comment]
> For those of you looking for a workaround, I think this will do the trick:
> 
> ```
> $assignTo = "BigHouseITGuy"
> 
> $jiraUserData = get-jirauser -UserName $assignTo -exact | Select-Object *
> 
> $accountIdObject = [pscustomobject]@{
>     accountId = $jiraUserData.accountId
> }
> 
> $fields = @{
>     'assignee' = $accountIdObject
> }
> 
> Set-JiraIssue -Issue $issue.key -Fields $fields
> ```
> 
> This also works for reporter.
Thanks . This solution works like a charm! You saved a lot of manual work!

**Comment by vyacheslavshcherbak** [comment]
Thanks @BigHouseITGuy . Your solution with small changes works for me too!

**Comment by LaurentGoderre** [comment]
@vyacheslavshcherbak I am not involved with this project, just a user like you who tried to debug this issue.

**Comment by rikkiprince** [comment]
Thank @BigHouseITGuy. That workaround was really helpful!
