### ISSUE TITLE
Cannot assign reporter

### ISSUE THREAD

**Issue by BigHouseITGuy** [AtlassianPS/JiraPS#405]
## Description

New-JiraIssue -Reporter tag is non-functional. When used, the reporter is left as "Anonymous" and when left blank the reporter is set to the currently authenticated user. 

## Steps To Reproduce

New-JiraIssue -Project "TEST" -IssueType "Incident" -Summary "Test" -Description $body -Reporter admin

## Expected behavior

The new issue should show a reporter of the admin user in this case. 

## Your Environment
Get-Module JiraPS -ListAvailable | Select Name, Version

Name   Version
----   -------
JiraPS 2.12.5 
JiraPS 2.12.4 
JiraPS 2.12.3 
JiraPS 2.11.1 

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.18362.628                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.18362.628                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by lipkau** [comment]
Thank you for reporting this.
This behavior has the same cause as #404 .
I am closing this as a duplicate. please follow that ticket for keeping up-to-date
