### ISSUE TITLE
data was not an object error

### ISSUE THREAD

**Issue by GradyD** [AtlassianPS/JiraPS#418]
Trying to create a ticket and no matter how I structure my params it always fails saying data was not an object.

![image](https://user-images.githubusercontent.com/994964/83045491-a4ec6500-a013-11ea-8d67-ec807c6b08d0.png)

```
$parameters = @{
    Project = "TEST"
    IssueType = "Ticket"
    Summary = 'Test issue from PowerShell'
    Description = 'This is a test issue created from the JiraPS module in PowerShell.'
    Fields = @{
        "components" = @(@{"name" = "TEST"})
        "Assignee" = @(@{"name" = "gduncan"})
        "reporter" = @(@{"name" = "gduncan"})
    }
}


New-JiraIssue @parameters
```

I have tried all sorts of ways of structing assignee and reporter. Can you tell me what I'm missing?

**Comment by GradyD** [comment]
````
Fields = @{
        "components" = @(@{"name" = "Test"})
        "Assignee" = @{"name" = "gduncan"}
        "reporter" = @{"name" = "gduncan"}
    }
````

Issue was asignee and reporter need the hashtable, but not the array.

**Comment by SleepyApache** [comment]
What was your solution?
