### ISSUE TITLE
Unable to retrieve data for custom fields

### ISSUE THREAD

**Issue by ankushbanerjee** [AtlassianPS/JiraPS#420]
I am using PSJira , I am issuing a command $OldIssues = Get-JiraIssue -Query 'project=<project_name> AND created >=-60d'
When I try to capture the value of a custom field that I know exists, I dont get any results.
Write-Host $OldIssues.customfield_<ID of the customfield>
But the KEY/Status/Summary fields return value.

How do I get the values of custom fields of a list of Issues in PSJira

**Comment by lipkau** [comment]
what version of the module are you using.
The module hasn't been called `PSJira` for over two years now.

But you can see all the fields the API returned with this:
```powershell
$oldIssues | fl *
```

**Comment by ankushbanerjee** [comment]
Thanks! Sorry it was a typo I was using JiraPS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdelforno** [comment]
#please-close
