### ISSUE TITLE
Kerberos authentication failed. Redirecting to standard login form. Invoke-JiraMethod

### ISSUE THREAD

**Issue by pkarunkar** [AtlassianPS/JiraPS#428]
## Description
using http://url:port
Throws kerberos authentication error. 
The credential may not be required since invoke-restmethod -userdefaultcredentials -userAgent "WindowsNT" is working fine. 
But not using this Module. How do I make this work without passing credentials. 

Set-JiraConfigServer "http://URI:port"
Get-jiraIssue -Key "Xyz" 

Cannot put screenshots since do not have external internet access from work.

**Comment by lipkau** [comment]
The module uses `Invoke-WebRequest` and not `Invoke-RestMethod`.

But to answer your question: you can use `$PSDefaultParameterValues` to set parameters on the underlying requests.
