### ISSUE TITLE
Set-JiraIssue does not accept pipeline input

### ISSUE THREAD

**Issue by agowa338** [AtlassianPS/JiraPS#433]
## Description

Set-JiraIssue does not accept pipeline input e.g. an object created by Get-JiraIssue
Also there is an attribute naming missmatch. Get-Jiraissue returns the ticket id within the Attribute "Key" where as Set-JiraIssue expects "Issue".

## Steps To Reproduce

1. `$ticket = Get-JiraIssue -Key $AnyTicketID`
2. `$ticket.Summary = "Lorem Ipsum"`
3. `$ticket | Set-JiraIssue` <= Failing because of unsupported pipeline input
4. `Set-JiraIssue @ticket` <= Failing because of different attribute names.

## Expected behavior

Ticket being updated.

**Comment by lipkau** [comment]
The current format of the Issue object does not support that.
This might be changed with the next major version of the module.
