### ISSUE TITLE
Get value of a custom field

### ISSUE THREAD

**Issue by JoachimAs** [AtlassianPS/JiraPS#449]
## Description

I don't know this is possible a bug. I would like to return the value of a custom field.

## Steps To Reproduce

`Get-JiraIssue -Key "HELP-863" -Fields "customfield_15360" -Credential $cred`

i get the ouput.

```
Key              Summary                                                                                                                                          Status                   Created
---              -------                                                                                                                                          ------                   -------
HELP-863
```

And thats all.

I hope is it posslible to help me.

**Comment by lipkau** [comment]
The data is there. It's just not shown in the console formatting rules.

![image](https://user-images.githubusercontent.com/4992870/154025993-218b5d60-a6d5-40c9-bf75-37743354a65f.png)

if you capture the output to a variable, you will be able to use it field.
