### ISSUE TITLE
When calling New-JiraIssue with custom required field, error is returned

### ISSUE THREAD

**Issue by banjoey** [AtlassianPS/JiraPS#48]
Resolve-JiraError : Jira encountered an error: [customfield_10301] - Can not instantiate value of type [simple type,class com.atlassian.jira.issue.fields.rest.json.beans.GroupJsonBean] from JSON String; no single-String constructor/factory method

Field is populated from a Group Picker control, and is a single selection field.

**Comment by replicaJunction** [comment]
Interesting. Any chance you could post the full New-JiraIssue command and the debug output?

**Comment by lipkau** [comment]
I will close this issue, as we are unable to reproduce the error.
Feel free to open another issue or ask to reopen.
