### ISSUE TITLE
Unable to install JiraPS or ConfluencePS

### ISSUE THREAD

**Issue by manojs888** [AtlassianPS/JiraPS#503]
In Powershell on WSL.

 Install-Package JiraPS
Install-Package: No match was found for the specified search criteria and package name 'JiraPS'. Try Get-PackageSource to see all available registered package sources.

Get-PackageSource

Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
nuget.org                        NuGet            False      https://api.nuget.org/v3/index.json

**Comment by mkellerman** [comment]
You need to use `Install-Module JiraPS`. Please try again and let us know.

**Comment by manojs888** [comment]
This article has resolved my issue, therefore we can close this ticket - thank you for your effort
https://daveshap.github.io/DavidShapiroBlog/powershell/kb/2021/03/12/install-powershell-modules.html
