### ISSUE TITLE
Unable to change the transition

### ISSUE THREAD

**Issue by gangadhar01a** [AtlassianPS/JiraPS#90]
Hi,

I was able to connect to jira through powershell and ran few command which are working as expected, I tried to execute the below command to change the status of a ticket 
"Get-JiraIssue -Query "project='TPFCG' and summary~'Forklift.OrderDrop deploy to 3pi'" -Credential $cred | Invoke-JiraIssueTransition -Transition 21"

It's throwing the below error

"WARNING: JIRA returned HTTP error 401 - Unauthorized
Resolve-JiraError : Jira encountered an error: [You do not have the permission to see the specified issue.]
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.160\Internal\Invoke-JiraMethod.ps1:111 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError"

I have provided the Jira Admin credentials while running the script. I was able to execute the commands to find out the transitions but unable to change it.

**Comment by z0ph** [comment]
Hi @gangadhar01a 

Did you tried your query on Jira ? Does it works as expected ?

Did you tried to make a filter of your query ?

Does a simple Get-Jira issue with the number of the ticket is working ?

**Comment by lipkau** [comment]
Hi @gangadhar01a 

I suppose `-Credential $cred` is not being used in the `Invoke-JiraIssueTransition` command
Please try:
```powershell
"Get-JiraIssue -Query "project='TPFCG' and summary~'Forklift.OrderDrop deploy to 3pi'" -Credential $cred | Invoke-JiraIssueTransition -Transition 21" -Credential $cred
```

**Comment by lipkau** [comment]
As this issue has been inactive for over a month, I am closing it.
Feel free to open a new issue
